# Generated by Django 2.1 on 2018-08-13 09:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainform', '0002_questionnaire_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionnaire',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
