# Generated by Django 2.1 on 2018-08-24 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainform', '0003_auto_20180813_1706'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['created_time']},
        ),
    ]
